# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dyne.CJIT
PackageVersion: 0.18.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dyne/cjit/releases/download/v0.18.1/CJIT_install.exe
  InstallerSha256: 429530E20E6346DB20E18294CF6FBEB1558B9A47099C49E52757DA6833DC520F
ManifestType: installer
ManifestVersion: 1.9.0
